[alembic]
script_location = app_repo
prepend_sys_path = .
sqlalchemy.url = mysql://root:2310@127.0.0.1/rite_db
#sqlalchemy.url = mssql+pyodbc://sa:meLleva05@admin_vacaciones_db:1433/AdminVacaciones?driver=ODBC+Driver+17+for+SQL+Server

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
