"""Create table new rites

Revision ID: 5c332235a789
Revises: 6a03f6fd2ff1
Create Date: 2025-09-04 16:12:16.208072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c332235a789'
down_revision = '6a03f6fd2ff1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
