"""Create table new rites

Revision ID: 6a03f6fd2ff1
Revises: f27fc82c9435
Create Date: 2025-09-04 16:04:52.235215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a03f6fd2ff1'
down_revision = 'f27fc82c9435'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(length=255), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=False),
    sa.Column('departure_time', sa.DateTime(), nullable=False),
    sa.Column('price_per_seat', sa.Float(), nullable=False),
    sa.Column('available_seats', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('upcoming', 'in_progress', 'completed', 'cancelled', name='ritestatus'), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('instructions', sa.String(length=500), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rites_id'), 'rites', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rites_id'), table_name='rites')
    op.drop_table('rites')
    # ### end Alembic commands ###
